spring:
  application:
    name: spring-cloud-dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

dubbo:
  scan:
    base-packages: org.springframework.cloud.alibaba.demo
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registries:
    new:
      address: spring-cloud://localhost

server:
  port: 11111

management:
  endpoints:
    web:
      exposure:
        include: dubborestmetadata