spring:
  application:
    name: spring-cloud-dubbo-consumer
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: ${provider.application.name}

server:
  port: 55555

provider:
  application:
    name: spring-cloud-dubbo-provider